// <auto-generated />
namespace CarsStore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changeID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeID));
        
        string IMigrationMetadata.Id
        {
            get { return "201901212304457_changeID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
